### ISSUE TITLE
Incorrect parsing of function pointer typedef

### ISSUE THREAD

**Issue by dolmen** [return42/sphkerneldoc#3]
This code is incorrectly parsed: `typedef void(*data_exchange_cb_t)`
The name part is `data_exchange_cb_t`, but the parser highlights `void`.

https://return42.github.io/sphkerneldoc/linux_src_doc/include/net/nfc/nfc_h.html#void

**Comment by return42** [comment]
Hi 'dolmen', thanks for remark, helps me to improve the kernel-doc parser. The parser is in my linuxdoc project, I fixed it there.

https://github.com/return42/linuxdoc/commit/d585de383c7f56604378e48e6b6c62bde0b9ecbf
